import { Button, Group } from '@mantine/core';
import Head from 'next/head';
import { useRouter } from 'next/router';
import RootLayout from '../components/RootLayout';

export default function Home() {
    const router = useRouter();
    const ButtonList = [
        {
            name: 'SpaceX History',
            path: '/history',
        },
        {
            name: 'SpaceX Payloads',
            path: '/payloads',
        },
    ];
    return (
        <div className='smv-flex smv-h-full  smv-w-full smv-items-center smv-justify-center '>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Group
                direction='column'
                className=' smv-items-center smv-justify-center smv-flex'
            >
                <text className=' smv-font-bold smv-text-4xl'>Welcome</text>
                <Group>
                    {ButtonList.map((button, index) => (
                        <Button
                            key={index}
                            onClick={() => router.push(`/${button?.path}`)}
                        >
                            {button?.name}
                        </Button>
                    ))}
                </Group>
            </Group>
        </div>
    );
}

Home.getLayout = function getLayout(page) {
    return <RootLayout>{page}</RootLayout>;
};
